apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-map
  namespace: default
data:
  prometheusImage: "ghcr.io/prometheus/prom:v2.0.0"
  image: "ghcr.io/example/sample:v2.2.0"
  enemies: "aliens"
  lives: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-map-yaml
  namespace: default
data:
  config: |
    prometheusImage: 'ghcr.io/prometheus/prom:v2.0.0'
    image: 'ghcr.io/example/sample:v2.2.0'
    enemies: aliens
    lives: '3'
    config:
      image: 'ghcr.io/example/config:v2.3.0'
      testConfig:
        testImage: 'ghcr.io/example/test:v2.3.0'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-map-json
  namespace: default
data:
  config: |
    {
      "prometheusImage": "ghcr.io/prometheus/prom:v2.0.0",
      "image": "ghcr.io/example/sample:v2.2.0",
      "enemies": "aliens",
      "lives": "3",
      "config": {
        "image": "ghcr.io/example/config:v2.3.0"
      }
    }